package com.hemsw.asasaapi.veenal.enums;

public enum FXMLLayouts
{
	// Add forms
	ACCT_CLEAR_UPTO_DIALOG("", "resources/view/AcctClearUptoDialog.fxml"),
	ACCT_CONTACT_NO("", "resources/view/AcctContactNo.fxml"),
	ACCT_GRP("", "resources/view/AcctGrp.fxml"),
	ACCT_LIST_FOR_CUSTOMER_DIALOG("", "resources/view/AcctListForCustomerDialog.fxml"),
	ACCT_LIST_FOR_SUPPLIER_DIALOG("", "resources/view/AcctListForSupplierDialog.fxml"),
	ACTIVATION("Activation", "resources/view/Activation.fxml"),
	ADD_ACCESS_ROLE("Access Role", "resources/view/AddAccessRole.fxml"),
	ADD_ACCT("Account", "resources/view/AddAcct.fxml"),
	ADD_ACCT_CUSTOMER_AGENT_SV("", "resources/view/AddAcctCustomerAgentSv.fxml"),
	ADD_ACCT_NEW("Account", "resources/view/AddAcctNew.fxml"),
	ADD_ACCT_SV("", "resources/view/AddAcctSv.fxml"),
	ADD_ACCT_AGENT_SV("", "resources/view/AddAcctAgentSv.fxml"),
	ADD_ACCT_BANK_SV("", "resources/view/AddAcctBankSv.fxml"),
	ADD_ACCT_CUSTOMER_SV("", "resources/view/AddAcctCustomerSv.fxml"),
	ADD_ACCT_SUPPLIER_SV("", "resources/view/AddAcctSupplierSv.fxml"),
	ADD_ACCT_TYPE("Account Type", "resources/view/AddAcctType.fxml"),
	ADD_AGENT("Agent", "resources/view/AddAgent.fxml"),
	ADD_BANK("Bank", "resources/view/AddBank.fxml"),
	ADD_CASH_SALES_RECEIPT("", "resources/view/AddCashSalesReceipt.fxml"),
	ADD_CDP_JOURNAL_VOU("Cash Discount / Penalty", "resources/view/AddCdpJournalVou.fxml"),
	ADD_COLOR("Color", "resources/view/AddColor.fxml"),
	ADD_COMMNC("Communication", "resources/view/AddCommnc.fxml"),
	ADD_COMM_LIST("Commission List", "resources/view/AddCommList.fxml"),
	ADD_COMM_LIST_CAT_SV("", "resources/view/AddCommListCatSv.fxml"),
	ADD_COMM_LIST_PROD_SV("", "resources/view/AddCommListProdSv.fxml"),
	ADD_COMPANY_PROFILE("Company Profile", "resources/view/AddCompanyProfile.fxml"),
	ADD_COMPANY_YEAR("Company Year", "resources/view/AddCompanyYear.fxml"),
	ADD_CONTRA("Contra", "resources/view/AddContra.fxml"),
	ADD_CUSTOMER("Customer", "resources/view/AddCustomer.fxml"),
	ADD_EDIT_DIALOG("", "resources/view/AddEditDialog.fxml"),
	ADD_ESTIMATE("Estimate", "resources/view/AddEstimate.fxml"),
	ADD_ESTIMATE_ITEM_FORM_SV("", "resources/view/AddEstimateItemFormSv.fxml"),
	ADD_ESTIMATE_ITEM_ROW_SV("", "resources/view/AddEstimateItemRowSv.fxml"),
	ADD_ESTIMATE_ITEM_SV("", "resources/view/AddEstimateItemSv.fxml"),
	ADD_HOSIERY_PRODUCT_OPENING_STOCK("", "resources/view/AddHosieryProductOpeningStock.fxml"),
	ADD_HOSIERY_PURCHASE_ITEM("", "resources/view/AddHosieryPurchaseItem.fxml"),
	ADD_HOSIERY_PURCHASE_RETURN_ITEM("", "resources/view/AddHosieryPurchaseReturnItem.fxml"),
	ADD_HOSIERY_SALES_ITEM("", "resources/view/AddHosierySalesItem.fxml"),
	ADD_HOSIERY_SALES_RETURN_ITEM("", "resources/view/AddHosierySalesReturnItem.fxml"),
	ADD_INV_ADJUST("Stock Journal", "resources/view/AddInvAdjust.fxml"),
	ADD_INV_ADJUST_IN_MFG_SV("", "resources/view/AddInvAdjustInMfgSv.fxml"),
	ADD_INV_ADJUST_IN_STOCK_SV("", "resources/view/AddInvAdjustInStockSv.fxml"),
	ADD_INV_ADJUST_IN_TOTAL_SV("", "resources/view/AddInvAdjustInTotalSv.fxml"),
	ADD_INV_ADJUST_OUT_OTH_CHARGE_SV("", "resources/view/AddInvAdjustOutOthChargeSv.fxml"),
	ADD_INV_ADJUST_OUT_SERVICE_SV("", "resources/view/AddInvAdjustOutServiceSv.fxml"),
	ADD_INV_ADJUST_OUT_SV("", "resources/view/AddInvAdjustOutSv.fxml"),
	ADD_INV_ADJUST_OUT_TOTAL_GEN_SV("", "resources/view/AddInvAdjustOutTotalGenSv.fxml"),
	ADD_INV_ADJUST_OUT_TOTAL_MFG_SV("", "resources/view/AddInvAdjustOutTotalMfgSv.fxml"),
	ADD_ISSUE_GOODS_FACTORY("Issue Goods", "resources/view/AddIssueGoodsFactory.fxml"),
	ADD_ISSUE_GOODS_JOB("Issue Goods", "resources/view/AddIssueGoodsJob.fxml"),
	ADD_ISSUE_GOODS_JOB_GEN("Issue Goods", "resources/view/AddIssueGoodsJobGen.fxml"),
	ADD_ISSUE_GOODS_JOB_GEN_ESTIMATE("Issue Goods", "resources/view/AddIssueGoodsJobGenEstimate.fxml"),
	ADD_ISSUE_GOODS_JOB_GEN_ITEM("Issue Goods", "resources/view/AddIssueGoodsJobGenItem.fxml"),
	ADD_ISSUE_GOODS_CV("", "resources/view/AddIssueGoodsCV.fxml"),
	ADD_ISSUE_GOODS_CV_SUMMARY("", "resources/view/AddIssueGoodsCVSummary.fxml"),
	ADD_ISSUE_GOODS_COLOR_QTY_PART("", "resources/view/AddIssueGoodsColorQtyPart.fxml"),
	ADD_ISSUE_GOODS_NCV("", "resources/view/AddIssueGoodsNCV.fxml"),
	ADD_ISSUE_GOODS_NCV_SUMMARY("", "resources/view/AddIssueGoodsNCVSummary.fxml"),
	ADD_JOB("Job", "resources/view/AddJob.fxml"),
	ADD_JOB_CV_ESTIMATED_QTY("", "resources/view/AddJobCVEstimatedQty.fxml"),
	ADD_JOB_COLOR_GROUP("", "resources/view/AddJobColorGroup.fxml"),
	ADD_JOB_COLOR_GROUP_ITEM("", "resources/view/AddJobColorGroupItem.fxml"),
	ADD_JOB_GEN("Job", "resources/view/AddJobGen.fxml"),
	ADD_JOB_NCV_ESTIMATED_QTY("", "resources/view/AddJobNCVEstimatedQty.fxml"),
	ADD_JOB_WORK("", "resources/view/AddJobWork.fxml"),
	ADD_JOURNAL("Journal", "resources/view/AddJournal.fxml"),
	ADD_JOURNAL_ITEM_SV("Journal", "resources/view/AddJournalItemSv.fxml"),
	ADD_LEAD("Lead", "resources/view/AddLead.fxml"),
	ADD_LEAD_SRC("Lead Source", "resources/view/AddLeadSrc.fxml"),
	ADD_LEAD_STATUS("Lead Status", "resources/view/AddLeadStatus.fxml"),
	ADD_MFG_PRODUCT("Manufacturing Product", "resources/view/AddMfgProduct.fxml"),
	ADD_ORDER_ADJUST("Order Adjust", "resources/view/AddOrderAdjust.fxml"),
	ADD_ORDER_ADJUST_ITEMS_ROW_SV("", "resources/view/AddOrderAdjustItemsRowSv.fxml"),
	ADD_ORDER_ADJUST_ITEMS_SV("", "resources/view/AddOrderAdjustItemsSv.fxml"),
	ADD_OTH_CHARGE("Voucher Other Charges", "resources/view/AddOthCharge.fxml"),
	ADD_PAYMENT("Payment", "resources/view/AddPayment.fxml"),
	ADD_PI("Proforma Invoice", "resources/view/AddPi.fxml"),
	ADD_PI_ITEM_SV("", "resources/view/AddPiItemSv.fxml"),
	ADD_PI_ITEM_FORM_SV("", "resources/view/AddPiItemFormSv.fxml"),
	ADD_PRODUCT("Product", "resources/view/AddProduct.fxml"),
	ADD_PRODUCT_BOM_OTH_CHARGE_SV("", "resources/view/AddProductBomOthChargeSv.fxml"),
	ADD_PRODUCT_DETAIL_SV("", "resources/view/AddProductDetailSv.fxml"),
	ADD_PRODUCT_CATEGORY("Product Category", "resources/view/AddProductCategory.fxml"),
	ADD_PRODUCT_COMPONENT("", "resources/view/AddProductComponent.fxml"),
	ADD_PRODUCT_COSTING("", "resources/view/AddProductCosting.fxml"),
	ADD_PRODUCT_OPENING_STOCK("", "resources/view/AddProductOpeningStock.fxml"),
	ADD_PRODUCT_OTH_CHARGE("Product Other Charge", "resources/view/AddProductOthCharge.fxml"),
	ADD_PRODUCT_WORK("", "resources/view/AddProductWork.fxml"),
	ADD_PURCHASE("Purchase", "resources/view/AddPurchase.fxml"),
	ADD_PURCHASE_ORDER("Purchase Order", "resources/view/AddPurchaseOrder.fxml"),
	ADD_PURCHASE_ORDER_ITEM_SV("", "resources/view/AddPurchaseOrderItemSv.fxml"),
	ADD_PURCHASE_ORDER_ITEM_FORM_SV("", "resources/view/AddPurchaseOrderItemFormSv.fxml"),
	ADD_PURCHASE_ITEM("", "resources/view/AddPurchaseItem.fxml"),
	ADD_PURCHASE_PRICE_LIST("Purchase Price List", "resources/view/AddPurchasePriceList.fxml"),
	ADD_PURCHASE_PRICE_LIST_PROD_SV("", "resources/view/AddPurchasePriceListProdSv.fxml"),
	ADD_PURCHASE_RETURN("Purchase Return", "resources/view/AddPurchaseReturn.fxml"),
	ADD_PURCHASE_RETURN_ITEM_FORM_SV("", "resources/view/AddPurchaseReturnItemFormSv.fxml"),
	ADD_PURCHASE_RETURN_ITEM_SV("", "resources/view/AddPurchaseReturnItemSv.fxml"),
	ADD_RATE("Rate", "resources/view/AddRate.fxml"),
	ADD_RCV_GOODS_JOB("Receive Goods", "resources/view/AddRcvGoodsJob.fxml"),
	ADD_RCV_GOODS_JOB_GEN("Receive Goods", "resources/view/AddRcvGoodsJobGen.fxml"),
	ADD_RCV_GOODS_JOB_GEN_ESTIMATE("Rate", "resources/view/AddRcvGoodsJobGenEstimate.fxml"),
	ADD_RCV_GOODS_JOB_GEN_ITEM("Receive Goods", "resources/view/AddRcvGoodsJobGenItem.fxml"),
	ADD_RCV_GOODS_MANUAL_GENERAL("Receive Goods", "resources/view/AddRcvGoodsManualGeneral.fxml"),
	ADD_RCV_GOODS_MANUAL_HOSIERY("Receive Goods", "resources/view/AddRcvGoodsManualHosiery.fxml"),
	ADD_RCV_GOODS_TYPE2("Receive Goods", "resources/view/AddRcvGoodsType2.fxml"),
	ADD_RCV_GOODS_TYPE2_PRODUCT_COMPO("", "resources/view/AddRcvGoodsType2ProductCompo.fxml"),
	ADD_RCV_GOODS_TYPE2_RATE("", "resources/view/AddRcvGoodsType2Rate.fxml"),
	ADD_RCV_GOODS_WORKER_PART("", "resources/view/AddRcvGoodsWorkerPart.fxml"),
	ADD_RECEIPT("Receipt", "resources/view/AddReceipt.fxml"),
	ADD_REMINDER("Reminder", "resources/view/AddReminder.fxml"),
	ADD_MESSAGE_TEMPLATE("Message Template", "resources/view/AddMessageTemplate.fxml"),
	ADD_SALES("Sales", "resources/view/AddSales.fxml"),
	ADD_SALES_ITEM_SV("", "resources/view/AddSalesItemSv.fxml"),
	ADD_SALES_ITEM_FORM_SV("", "resources/view/AddSalesItemFormSv.fxml"),
	ADD_SALES_ORDER("Sales Order", "resources/view/AddSalesOrder.fxml"),
	ADD_SALES_ORDER_ITEM_FORM_SV("", "resources/view/AddSalesOrderItemFormSv.fxml"),
	ADD_SALES_ORDER_ITEM_ROW_SV("", "resources/view/AddSalesOrderItemRowSv.fxml"),
	ADD_SALES_ORDER_ITEM_SV("", "resources/view/AddSalesOrderItemSv.fxml"),
	ADD_SALES_ORDER_PENDING_ITEM_FORM_SV("", "resources/view/AddSalesOrderPendingItemSv.fxml"),
	ADD_SALES_PRICE_LIST("Sales Price List", "resources/view/AddSalesPriceList.fxml"),
	ADD_SALES_PRICE_LIST_PROD_SV("", "resources/view/AddSalesPriceListProdSv.fxml"),
	ADD_SALES_RETURN("Sales Return", "resources/view/AddSalesReturn.fxml"),
	ADD_SALES_RETURN_ITEM_SV("", "resources/view/AddSalesReturnItemSv.fxml"),
	ADD_SALES_RETURN_ITEM_FORM_SV("", "resources/view/AddSalesReturnItemFormSv.fxml"),
	ADD_SERVICE("Service", "resources/view/AddService.fxml"),
	ADD_SUPPLIER("Supplier", "resources/view/AddSupplier.fxml"),
	ADD_TAX("Tax", "resources/view/AddTax.fxml"),
	ADD_TAX_CAT("Tax Category", "resources/view/AddTaxCat.fxml"),
	ADD_TAX_CAL_RATE("Tax Calculation Rate", "resources/view/AddTaxCalRate.fxml"),
	ADD_TRANSPORTER("Transporter", "resources/view/AddTransporter.fxml"),
	ADD_UNIT("Unit", "resources/view/AddUnit.fxml"),
	ADD_USER("User", "resources/view/AddUser.fxml"),
	ADD_WORK("Work", "resources/view/AddWork.fxml"),
	ADD_WORKER("Worker", "resources/view/AddWorker.fxml"),
	ADD_YEAR("Financial Year", "resources/view/AddYear.fxml"),
	BUS_INFO("Business Information", "resources/view/BusInfo.fxml"),
	BUS_SETTING("Business Setting", "resources/view/BusSetting.fxml"),
	BUTTON_BAR_4_LIST("", "resources/view/ButtonBar4List.fxml"),
	CDP_JOURNAL_EXPORT_DIALOG("", "resources/view/CdpJournalExportDialog.fxml"),
	CDP_JOURNAL_GENERATE_DIALOG("", "resources/view/CdpJournalGenerateDialog.fxml"),
	COL("Column Setting", "resources/view/Col.fxml"),
	COL_ORDER("Company Information", "resources/view/ColOrder.fxml"),
	COL_ORDER_ROW("Company Information", "resources/view/ColOrderRow.fxml"),
	COL_SELECT("Company Information", "resources/view/ColSelect.fxml"),
	COMPANY_INFO("Company Information", "resources/view/CompanyInfo.fxml"),
	COMMNC_ASSIGN_TO("Communiction Assign To", "resources/view/CommncAssignTo.fxml"),
	COMMNC_BOOK("Communiction Book", "resources/view/CommncBook.fxml"),
	CUSTOMER_AGENT_COMM_LIST_SV("", "resources/view/CustomerAgentCommListSv.fxml"),
	CUSTOMER_AGENT_COMM_SV("", "resources/view/CustomerAgentCommSv.fxml"),
	CUSTOMER_DISC_SV("", "resources/view/CustomerDiscSv.fxml"),
	CUSTOMER_PRICE_LIST_A_SV("", "resources/view/CustomerPriceListASv.fxml"),
	CUSTOMER_PRICE_LIST_B_SV("", "resources/view/CustomerPriceListBSv.fxml"),
	CUSTOMER_SELECTION_SV("", "resources/view/CustomerSelectionSv.fxml"),
	COMM_LIST_SV("", "resources/view/CommListSv.fxml"),
	COMM_SV("", "resources/view/CommSv.fxml"),
	EDIT_COMMNC_LOG("Communication Log", "resources/view/EditCommncLog.fxml"),
	EDIT_COMPANY("Company", "resources/view/EditCompany.fxml"),
	EDIT_LEAD("Lead", "resources/view/EditLead.fxml"),
	EDIT_REMINDER("Reminder Edit", "resources/view/EditReminder.fxml"),
	ENTRY_TYPE_DIALOG("", "resources/view/EntryTypeDialog.fxml"),
	ERROR_DIALOG("", "resources/view/ErrorDialog.fxml"),
	ESTIMATE_PRINT_TYPE_DIALOG("", "resources/view/EstimatePrintTypeDialog.fxml"),
	ESTIMATE_PROD_DIALOG("", "resources/view/EstimateProdDialog.fxml"),
	IMPORT_DATA("", "resources/view/ImportData.fxml"),
	IMPORT_PRODUCT("Import Product", "resources/view/ImportProduct.fxml"),
	KB_SHORTCUT("Keyboard Shortcuts", "resources/view/KbShortcut.fxml"),
	KB_SHORTCUT_ROW_SV("", "resources/view/KbShortcutRowSv.fxml"),
	LEAD_VIEW_SV("", "resources/view/LeadViewSv.fxml"),
	NOTIFICATION("", "resources/view/Notification.fxml"),
	REMINDER_RESCHED("Reminder Reschedule", "resources/view/ReminderResched.fxml"),
	REMINDER_SNOOZE("Reminder Snooze", "resources/view/ReminderSnooze.fxml"),
	REMINDER_TURN_OFF("Reminder Turn Off", "resources/view/ReminderTurnOff.fxml"),
	RPT_LEDGER_RELATED_REPORTS_DIALOG("Relaed Reports", "resources/view/RptLedgerRelatedReportsDialog.fxml"),
	RPT_TRIAL_BAL_RELATED_REPORTS_DIALOG("Relaed Reports", "resources/view/RptTrialBalRelatedReportsDialog.fxml"),
	SALES_RIGHT_WRONG_SV("", "resources/view/SalesRightWrongSv.fxml"),
	//
	LIST_SECTION_1("", "resources/view/ListSection1.fxml"),
	LIST_SECTION_2("", "resources/view/ListSection2.fxml"),
	LIST_SECTION_3("", "resources/view/ListSection3.fxml"),
	// List forms
	LIST_ACCESS_ROLE("Access Role", "resources/view/list/ListAccessRole.fxml"),
	LIST_ACCT("Accounts", "resources/view/list/ListAcct.fxml"),
	LIST_ACCT_TYPE("Account Types", "resources/view/list/ListAcctType.fxml"),
	LIST_AGENT("Agent", "resources/view/list/ListAgent.fxml"),
	LIST_BANK("Bank", "resources/view/list/ListBank.fxml"),
	LIST_CASH_DISC_VOU("Cash Discount Voucher", "resources/view/list/ListCashDiscVou.fxml"),
	LIST_CDP_JOURNAL_VOU("Cash Discount / Penalty", "resources/view/list/ListCdpJournalVou.fxml"),
	LIST_COLOR("Color", "resources/view/list/ListColor.fxml"),
	LIST_COMMNC("Communication", "resources/view/list/ListCommnc.fxml"),
	LIST_COMM_LIST("Commission List", "resources/view/list/ListCommList.fxml"),
	LIST_COMM_VOU("Commission Voucher", "resources/view/list/ListCommVou.fxml"),
	LIST_COMPANY_PROFILE("Company Profile", "resources/view/list/ListCompanyProfile.fxml"),
	LIST_CONTRA("Contra", "resources/view/list/ListContra.fxml"),
	LIST_CUSTOMER("Customer", "resources/view/list/ListCustomer.fxml"),
	LIST_ESTIMATE("Estimate", "resources/view/list/ListEstimate.fxml"),
	LIST_INV_ADJUST("Inventory Adjust", "resources/view/list/ListInvAdjust.fxml"),
	LIST_ISSUE_GOODS_JOB("Issue Goods", "resources/view/list/ListIssueGoodsJob.fxml"),
	LIST_ISSUE_GOODS_FACTORY("Issue Goods", "resources/view/list/ListIssueGoodsFactory.fxml"),
	LIST_JOB("Job", "resources/view/list/ListJob.fxml"),
	LIST_JOB_GEN("Job (General)", "resources/view/list/ListJobGen.fxml"),
	LIST_JOB_WORK_AMT("Job Work", "resources/view/list/ListJobWorkAmt.fxml"),
	LIST_JOB_WORKER("Job Worker", "resources/view/list/ListJobWorker.fxml"),
	LIST_JOURNAL("Journal", "resources/view/list/ListJournal.fxml"),
	LIST_LEAD("Lead", "resources/view/list/ListLead.fxml"),
	LIST_LEAD_SRC("Lead Source", "resources/view/list/ListLeadSrc.fxml"),
	LIST_LEAD_STATUS("Lead Status", "resources/view/list/ListLeadStatus.fxml"),
	LIST_MFG_PRODUCT("Manufacturing Product", "resources/view/list/ListMfgProduct.fxml"),
	LIST_MSG_QUEUE("Message Queue", "resources/view/list/ListMsgQueue.fxml"),
	LIST_ORDER_ADJUST("Order Adjust", "resources/view/list/ListOrderAdjust.fxml"),
	LIST_OTH_CHARGE("Voucher Other Charge", "resources/view/list/ListOthCharge.fxml"),
	LIST_PAYMENT("Payment", "resources/view/list/ListPayment.fxml"),
	LIST_PI("Proforma Invoice", "resources/view/list/ListPi.fxml"),
	LIST_PRODUCT("Product", "resources/view/list/ListProduct.fxml"),
	LIST_PRODUCT_CATEGORY("Product Category", "resources/view/list/ListProductCategory.fxml"),
	LIST_PRODUCT_OTH_CHARGE("Product Other Charge", "resources/view/list/ListProductOthCharge.fxml"),
	LIST_PURCHASE("Purchase", "resources/view/list/ListPurchase.fxml"),
	LIST_PURCHASE_ORDER("Purchase Order", "resources/view/list/ListPurchaseOrder.fxml"),
	LIST_PURCHASE_RETURN("Purchase Return", "resources/view/list/ListPurchaseReturn.fxml"),
	LIST_RATE("Rate", "resources/view/list/ListRate.fxml"),
	LIST_RCV_GOODS("Receive Goods", "resources/view/list/ListRcvGoods.fxml"),
	LIST_RECEIPT("Receipt", "resources/view/list/ListReceipt.fxml"),
	LIST_REMINDER("Reminder", "resources/view/list/ListReminder.fxml"),
	LIST_MSG_TEMPLATE("Message Template", "resources/view/list/ListMsgTemplate.fxml"),
	LIST_PURCHASE_PRICE_LIST("Purchase Price List", "resources/view/list/ListPurchasePriceList.fxml"),
	LIST_SALES("Sales", "resources/view/list/ListSales.fxml"),
	LIST_SALES_ORDER("Sales Order", "resources/view/list/ListSalesOrder.fxml"),
	LIST_SALES_PRICE_LIST("Sales Price List", "resources/view/list/ListSalesPriceList.fxml"),
	LIST_SALES_RETURN("Sales Return", "resources/view/list/ListSalesReturn.fxml"),
	LIST_SERVICE("", "resources/view/list/ListService.fxml"),
	LIST_SUPPLIER("Supplier", "resources/view/list/ListSupplier.fxml"),
	LIST_TAX("Tax", "resources/view/list/ListTax.fxml"),
	LIST_TAX_CAT("Tax Category", "resources/view/list/ListTaxCat.fxml"),
	LIST_TAX_CAL_RATE("Tax Calculation Rate", "resources/view/list/ListTaxCalRate.fxml"),
	LIST_TRANSPORTER("Transporter", "resources/view/list/ListTransporter.fxml"),
	LIST_UNIT("Unit", "resources/view/list/ListUnit.fxml"),
	LIST_USER("User", "resources/view/list/ListUser.fxml"),
	LIST_WORK("Work", "resources/view/list/ListWork.fxml"),
	LIST_WORKER("Worker", "resources/view/list/ListWorker.fxml"),
	// Search dialog
	LIST_ACCESS_ROLE_SEARCH_DIALOG("", "resources/view/sd/ListAccessRoleSearchDialog.fxml"),
	LIST_ACCT_SEARCH_DIALOG("", "resources/view/sd/ListAcctSearchDialog.fxml"),
	LIST_ACCT_TYPE_SEARCH_DIALOG("", "resources/view/sd/ListAcctTypeSearchDialog.fxml"),
	LIST_AGENT_SEARCH_DIALOG("", "resources/view/sd/ListAgentSearchDialog.fxml"),
	LIST_BANK_SEARCH_DIALOG("", "resources/view/sd/ListBankSearchDialog.fxml"),
	LIST_CASH_DISC_VOU_SEARCH_DIALOG("", "resources/view/sd/ListCashDiscVouSearchDialog.fxml"),
	LIST_CDP_JOURNAL_VOU_SEARCH_DIALOG("", "resources/view/sd/ListCdpJournalVouSearchDialog.fxml"),
	LIST_COLOR_SEARCH_DIALOG("", "resources/view/sd/ListColorSearchDialog.fxml"),
	LIST_COMMNC_SEARCH_DIALOG("", "resources/view/sd/ListCommncSearchDialog.fxml"),
	LIST_COMM_LIST_SEARCH_DIALOG("", "resources/view/sd/ListCommListSearchDialog.fxml"),
	LIST_COMM_VOU_SEARCH_DIALOG("", "resources/view/sd/ListCommVouSearchDialog.fxml"),
	LIST_COMPANY_PROFILE_SEARCH_DIALOG("", "resources/view/sd/ListCompanyProfileSearchDialog.fxml"),
	LIST_CONTRA_SEARCH_DIALOG("", "resources/view/sd/ListContraSearchDialog.fxml"),
	LIST_CUSTOMER_SEARCH_DIALOG("", "resources/view/sd/ListCustomerSearchDialog.fxml"),
	LIST_ESTIMATE_SEARCH_DIALOG("", "resources/view/sd/ListEstimateSearchDialog.fxml"),
	LIST_INV_ADJUST_SEARCH_DIALOG("", "resources/view/sd/ListInvAdjustSearchDialog.fxml"),
	LIST_ISSUE_GOODS_JOB_SEARCH_DIALOG("", "resources/view/sd/ListIssueGoodsJobSearchDialog.fxml"),
	LIST_ISSUE_GOODS_FACTORY_SEARCH_DIALOG("", "resources/view/sd/ListIssueGoodsFactorySearchDialog.fxml"),
	LIST_JOURNAL_SEARCH_DIALOG("", "resources/view/sd/ListJournalSearchDialog.fxml"),
	LIST_LEAD_SEARCH_DIALOG("", "resources/view/sd/ListLeadSearchDialog.fxml"),
	LIST_LEAD_SRC_SEARCH_DIALOG("", "resources/view/sd/ListLeadSrcSearchDialog.fxml"),
	LIST_LEAD_STATUS_SEARCH_DIALOG("", "resources/view/sd/ListLeadStatusSearchDialog.fxml"),
	LIST_MFG_PRODUCT_SEARCH_DIALOG("", "resources/view/sd/ListMfgProductSearchDialog.fxml"),
	LIST_MSG_QUEUE_SEARCH_DIALOG("", "resources/view/sd/ListMsgQueueSearchDialog.fxml"),
	LIST_ORDER_ADJUST_SEARCH_DIALOG("", "resources/view/sd/ListOrderAdjustSearchDialog.fxml"),
	LIST_OTH_CHARGE_SEARCH_DIALOG("", "resources/view/sd/ListOthChargeSearchDialog.fxml"),
	LIST_PAYMENT_SEARCH_DIALOG("", "resources/view/sd/ListPaymentSearchDialog.fxml"),
	LIST_PI_SEARCH_DIALOG("", "resources/view/sd/ListPiSearchDialog.fxml"),
	LIST_PRODUCT_SEARCH_DIALOG("", "resources/view/sd/ListProductSearchDialog.fxml"),
	LIST_PRODUCT_CATEGORY_SEARCH_DIALOG("", "resources/view/sd/ListProductCategorySearchDialog.fxml"),
	LIST_PRODUCT_OTH_CHARGE_SEARCH_DIALOG("", "resources/view/sd/ListProductOthChargeSearchDialog.fxml"),
	LIST_PURCHASE_PRICE_LIST_SEARCH_DIALOG("", "resources/view/sd/ListPurchasePriceListSearchDialog.fxml"),
	LIST_PURCHASE_SEARCH_DIALOG("", "resources/view/sd/ListPurchaseSearchDialog.fxml"),
	LIST_PURCHASE_ORDER_SEARCH_DIALOG("", "resources/view/sd/ListPurchaseOrderSearchDialog.fxml"),
	LIST_PURCHASE_RETURN_SEARCH_DIALOG("", "resources/view/sd/ListPurchaseReturnSearchDialog.fxml"),
	LIST_RATE_SEARCH_DIALOG("", "resources/view/sd/ListRateSearchDialog.fxml"),
	LIST_RCV_GOODS_SEARCH_DIALOG("", "resources/view/sd/ListRcvGoodsSearchDialog.fxml"),
	LIST_RECEIPT_SEARCH_DIALOG("", "resources/view/sd/ListReceiptSearchDialog.fxml"),
	LIST_REMINDER_SEARCH_DIALOG("", "resources/view/sd/ListReminderSearchDialog.fxml"),
	LIST_MSG_TEMPLATE_SEARCH_DIALOG("", "resources/view/sd/ListMsgTemplateSearchDialog.fxml"),
	LIST_SALES_SEARCH_DIALOG("", "resources/view/sd/ListSalesSearchDialog.fxml"),
	LIST_SALES_ORDER_SEARCH_DIALOG("", "resources/view/sd/ListSalesOrderSearchDialog.fxml"),
	LIST_SALES_PRICE_LIST_SEARCH_DIALOG("", "resources/view/sd/ListSalesPriceListSearchDialog.fxml"),
	LIST_SALES_RETURN_SEARCH_DIALOG("", "resources/view/sd/ListSalesReturnSearchDialog.fxml"),
	LIST_SERVICE_SEARCH_DIALOG("", "resources/view/sd/ListServiceSearchDialog.fxml"),
	LIST_SUPPLIER_SEARCH_DIALOG("", "resources/view/sd/ListSupplierSearchDialog.fxml"),
	LIST_TAX_SEARCH_DIALOG("", "resources/view/sd/ListTaxSearchDialog.fxml"),
	LIST_TAX_CAT_SEARCH_DIALOG("", "resources/view/sd/ListTaxCatSearchDialog.fxml"),
	LIST_TAX_CAL_RATE_SEARCH_DIALOG("", "resources/view/sd/ListTaxCalRateSearchDialog.fxml"),
	LIST_TRANSPORTER_SEARCH_DIALOG("", "resources/view/sd/ListTransporterSearchDialog.fxml"),
	LIST_UNIT_SEARCH_DIALOG("", "resources/view/sd/ListUnitSearchDialog.fxml"),
	LIST_USER_SEARCH_DIALOG("", "resources/view/sd/ListUserSearchDialog.fxml"),
	LIST_WORK_SEARCH_DIALOG("", "resources/view/sd/ListWorkSearchDialog.fxml"),
	LIST_WORKER_SEARCH_DIALOG("", "resources/view/sd/ListWorkerSearchDialog.fxml"),
	//
	REPORT_BALANCE_SHEET("Balance Sheet", "resources/view/list/ReportBalanceSheet.fxml"),
	REPORT_CURRENT_STOCK("Current Stock", "resources/view/list/ReportCurrentStock.fxml"),
	REPORT_CURRENT_STOCK_VAL("Current Stock Value", "resources/view/list/ReportCurrentStockVal.fxml"),
	REPORT_CASH_DISC_VOU_LEDGER("Cash Discount Voucher Ledger Report", "resources/view/list/ReportCashDiscVouLedger.fxml"),
	REPORT_CASH_DISC_VOU_LEDGER_2("Cash Discount Voucher Ledger Report 2", "resources/view/list/ReportCashDiscVouLedger2.fxml"),
	REPORT_COMM_VOU_LEDGER("Commission Voucher Ledger Report", "resources/view/list/ReportCommVouLedger.fxml"),
	REPORT_DAY_BOOK("Day Book", "resources/view/list/ReportDayBook.fxml"),
	REPORT_GST_LEDGER("GST Ledger", "resources/view/list/ReportGSTLedger.fxml"),
	REPORT_INVENTORY_LEDGER("Inventory Ledger", "resources/view/list/ReportInventoryLedger.fxml"),
	REPORT_LEDGER("Ledger", "resources/view/list/ReportLedger.fxml"),
	REPORT_LOW_STOCK("Low Stock", "resources/view/list/ReportLowStock.fxml"),
	REPORT_PNL_ACCT("Profit And Loss Account", "resources/view/list/ReportPnlAcct.fxml"),
	REPORT_SALES_ANALYSIS("Sales Analysis", "resources/view/list/ReportSalesAnalysis.fxml"),
	REPORT_SALES_ORDER_PENDING("Sales Order Pending", "resources/view/list/ReportSalesOrderPending.fxml"),
	REPORT_PURCHASE_ORDER_PENDING("Purchase Order Pending", "resources/view/list/ReportPurchaseOrderPending.fxml"),
	REPORT_TRADING_ACCOUNT("Trading Account", "resources/view/list/ReportTradingAccount.fxml"),
	RPT_ACCT_SUMM_BY_ACCT_TYPE("Account Summary", "resources/view/list/RptAcctSummByAcctType.fxml"),
	REPORT_TRIAL_BALANCE("Trial Balance", "resources/view/list/ReportTrialBalance.fxml"),
	REPORT_WORKER_WORK_SUMMARY("Ledger", "resources/view/list/ReportWorkerWorkSummary.fxml"),
	//
	RPT_SALES_RETURN_BY_AGENT("Sales Return Report By Agent", "resources/view/list/RptSalesReturnByAgent.fxml"),
	RPT_SALES_RETURN_BY_CITY("Sales Return Report By City", "resources/view/list/RptSalesReturnByCity.fxml"),
	RPT_SALES_RETURN_BY_CUSTOMER("Sales Return Report By Customer", "resources/view/list/RptSalesReturnByCustomer.fxml"),
	RPT_SALES_RETURN_BY_DAY("Sales Return Report By Day", "resources/view/list/RptSalesReturnByDay.fxml"),
	RPT_SALES_RETURN_BY_MONTH("Sales Return Report By Month", "resources/view/list/RptSalesReturnByMonth.fxml"),
	RPT_SALES_RETURN_BY_PROD_CAT("Sales Return Report By Product Category", "resources/view/list/RptSalesReturnByProdCat.fxml"),
	RPT_SALES_RETURN_BY_PROD("Sales Return Report By Product", "resources/view/list/RptSalesReturnByProd.fxml"),
	RPT_SALES_RETURN_BY_STATE("Sales Return Report By State", "resources/view/list/RptSalesReturnByState.fxml"),
	RPT_SALES_RETURN_DETAILED_BY_VOUCHER("Sales Return Report Detailed By Voucher", "resources/view/list/RptSalesReturnDetailedByVoucher.fxml"),
	RPT_SALES_RETURN_DETAILED_BY_PROD("Sales Return Report Detailed By Product", "resources/view/list/RptSalesReturnDetailedByProd.fxml"),
	//
	RPT_SALES_BY_AGENT("Sales Report By Agent", "resources/view/list/RptSalesByAgent.fxml"),
	RPT_SALES_BY_CITY("Sales Report By City", "resources/view/list/RptSalesByCity.fxml"),
	RPT_SALES_BY_CUSTOMER("Sales Report By Customer", "resources/view/list/RptSalesByCustomer.fxml"),
	RPT_SALES_BY_DAY("Sales Report By Day", "resources/view/list/RptSalesByDay.fxml"),
	RPT_SALES_BY_MONTH("Sales Report By Month", "resources/view/list/RptSalesByMonth.fxml"),
	RPT_SALES_BY_PROD_CAT("Sales Report By Product Category", "resources/view/list/RptSalesByProdCat.fxml"),
	RPT_SALES_BY_PROD("Sales Report By Product", "resources/view/list/RptSalesByProd.fxml"),
	RPT_SALES_BY_STATE("Sales Report By State", "resources/view/list/RptSalesByState.fxml"),
	RPT_SALES_DETAILED_BY_VOUCHER("Sales Report Detailed By Voucher", "resources/view/list/RptSalesDetailedByVoucher.fxml"),
	RPT_SALES_DETAILED_BY_PROD("Sales Report Detailed By Product", "resources/view/list/RptSalesDetailedByProd.fxml"),
	DUE_RCVABLE_BY_SALES("Due Receivables By Sales", "resources/view/list/DueRcvableBySales.fxml"),
	DUE_RCVABLE_BY_CUSTOMER("Due Receivables By Customer", "resources/view/list/DueRcvableByCustomer.fxml"),
	//
	//
	RPT_SALES_PROFIT_BY_CUSTOMER("Sales Profit By Customer", "resources/view/list/RptSalesProfitByCustomer.fxml"),
	RPT_SALES_PROFIT_BY_PROD("Sales Profit By Product", "resources/view/list/RptSalesProfitByProduct.fxml"),
	RPT_SALES_PROFIT_BY_SALES_ITEM("Sales Profit By Sales Item", "resources/view/list/RptSalesProfitBySalesItem.fxml"),
	RPT_SALES_PROFIT_BY_SALES_VOUCHER("Sales Profit By Sales Voucher", "resources/view/list/RptSalesProfitBySalesVoucher.fxml"),
	//
	//
	RPT_PURCHASE_RETURN_BY_AGENT("Purchase Return Report By Agent", "resources/view/list/RptPurchaseReturnByAgent.fxml"),
	RPT_PURCHASE_RETURN_BY_CITY("Purchase Return Report By City", "resources/view/list/RptPurchaseReturnByCity.fxml"),
	RPT_PURCHASE_RETURN_BY_SUPPLIER("Purchase Return Report By Supplier", "resources/view/list/RptPurchaseReturnBySupplier.fxml"),
	RPT_PURCHASE_RETURN_BY_DAY("Purchase Return Report By Day", "resources/view/list/RptPurchaseReturnByDay.fxml"),
	RPT_PURCHASE_RETURN_BY_MONTH("Purchase Return Report By Month", "resources/view/list/RptPurchaseReturnByMonth.fxml"),
	RPT_PURCHASE_RETURN_BY_PROD_CAT("Purchase Return Report By Product Category", "resources/view/list/RptPurchaseReturnByProdCat.fxml"),
	RPT_PURCHASE_RETURN_BY_PROD("Purchase Return Report By Product", "resources/view/list/RptPurchaseReturnByProd.fxml"),
	RPT_PURCHASE_RETURN_BY_STATE("Purchase Return Report By State", "resources/view/list/RptPurchaseReturnByState.fxml"),
	RPT_PURCHASE_RETURN_DETAILED_BY_VOUCHER("Purchase Return Report Detailed By Voucher", "resources/view/list/RptPurchaseReturnDetailedByVoucher.fxml"),
	RPT_PURCHASE_RETURN_DETAILED_BY_PROD("Purchase Return Report Detailed By Product", "resources/view/list/RptPurchaseReturnDetailedByProd.fxml"),
	//
	RPT_PURCHASE_BY_AGENT("Purchase Report By Agent", "resources/view/list/RptPurchaseByAgent.fxml"),
	RPT_PURCHASE_BY_CITY("Purchase Report By City", "resources/view/list/RptPurchaseByCity.fxml"),
	RPT_PURCHASE_BY_SUPPLIER("Purchase Report By Supplier", "resources/view/list/RptPurchaseBySupplier.fxml"),
	RPT_PURCHASE_BY_DAY("Purchase Report By Day", "resources/view/list/RptPurchaseByDay.fxml"),
	RPT_PURCHASE_BY_MONTH("Purchase Report By Month", "resources/view/list/RptPurchaseByMonth.fxml"),
	RPT_PURCHASE_BY_PROD_CAT("Purchase Report By Product Category", "resources/view/list/RptPurchaseByProdCat.fxml"),
	RPT_PURCHASE_BY_PROD("Purchase Report By Product", "resources/view/list/RptPurchaseByProd.fxml"),
	RPT_PURCHASE_BY_STATE("Purchase Report By State", "resources/view/list/RptPurchaseByState.fxml"),
	RPT_PURCHASE_DETAILED_BY_VOUCHER("Purchase Report Detailed By Voucher", "resources/view/list/RptPurchaseDetailedByVoucher.fxml"),
	RPT_PURCHASE_DETAILED_BY_PROD("Purchase Report Detailed By Product", "resources/view/list/RptPurchaseDetailedByProd.fxml"),
	//
	RPT_ESTIMATE_PENDING_BY_PROD("Estimate Pending By Product", "resources/view/list/RptEstimatePendingByProd.fxml"),
	RPT_ESTIMATE_PENDING_BY_ACCT("Estimate Pending By Customer", "resources/view/list/RptEstimatePendingByAcct.fxml"),
	RPT_ESTIMATE_PENDING_DET("Estimate Pending Product", "resources/view/list/RptEstimatePendingDet.fxml"),
	//
	RPT_IO_DET("Inventory Inward/Outward Detailed", "resources/view/list/RptIoDet.fxml"),
	RPT_IO_SUMM_BY_PROD_CAT("Inventory Inward/Outward Summary By Product Category", "resources/view/list/RptIoSummByProdCat.fxml"),
	RPT_IO_SUMM_BY_PROD("Inventory Inward/Outward Summary By Product", "resources/view/list/RptIoSummByProd.fxml"),
	RPT_IO_SUMM_BY_MONTH("Inventory Inward/Outward Summary By Month", "resources/view/list/RptIoSummByMonth.fxml"),
	// Report Search Dialog
	REPORT_CURRENT_STOCK_SEARCH_DIALOG("Current Stock", "resources/view/sd/ReportCurrentStockSearchDialog.fxml"),
	REPORT_CURRENT_STOCK_VAL_SEARCH_DIALOG("Current Stock", "resources/view/sd/ReportCurrentStockValSearchDialog.fxml"),
	REPORT_LOW_STOCK_SEARCH_DIALOG("Current Stock", "resources/view/sd/ReportLowStockSearchDialog.fxml"),
	REPORT_CASH_DISC_VOU_LEDGER_SEARCH_DIALOG("Cash Discount Voucher Ledger Report", "resources/view/sd/ReportCashDiscVouLedgerSearchDialog.fxml"),
	REPORT_CASH_DISC_VOU_LEDGER_2_SEARCH_DIALOG("Cash Discount Voucher Ledger Report 2", "resources/view/sd/ReportCashDiscVouLedger2SearchDialog.fxml"),
	REPORT_COMM_VOU_LEDGER_SEARCH_DIALOG("Commission Voucher Ledger Report", "resources/view/sd/ReportCommVouLedgerSearchDialog.fxml"),
	REPORT_DAY_BOOK_SEARCH_DIALOG("Day Book", "resources/view/sd/ReportDayBookSearchDialog.fxml"),
	REPORT_GST_LEDGER_SEARCH_DIALOG("GST Ledger", "resources/view/sd/ReportGSTLedgerSearchDialog.fxml"),
	REPORT_INVENTORY_LEDGER_SEARCH_DIALOG("Inventory Ledger", "resources/view/sd/ReportInventoryLedgerSearchDialog.fxml"),
	REPORT_LEDGER_SEARCH_DIALOG("Ledger", "resources/view/sd/ReportLedgerSearchDialog.fxml"),
	REPORT_PL_ACCOUNT_SEARCH_DIALOG("Profit And Loss Account", "resources/view/sd/ReportPLAccountSearchDialog.fxml"),
	REPORT_SALES_ANALYSIS_SEARCH_DIALOG("Sales Analysis", "resources/view/sd/ReportSalesAnalysisSearchDialog.fxml"),
	REPORT_SALES_ORDER_PENDING_SEARCH_DIALOG("Sales Order Pending", "resources/view/sd/ReportSalesOrderPendingSearchDialog.fxml"),
	REPORT_PURCHASE_ORDER_PENDING_SEARCH_DIALOG("Purchase Order Pending", "resources/view/sd/ReportPurchaseOrderPendingSearchDialog.fxml"),
	REPORT_TRADING_ACCOUNT_SEARCH_DIALOG("Trading Account", "resources/view/sd/ReportTradingAccountSearchDialog.fxml"),
	RPT_ACCT_SUMM_BY_ACCT_TYPE_SEARCH_DIALOG("Account Summary", "resources/view/sd/RptAcctSummByAcctTypeDialog.fxml"),
	RPT_TRIAL_BAL_SEARCH_DIALOG("Account Summary", "resources/view/sd/RptTrialBalSearchDialog.fxml"),
	REPORT_WORKER_WORK_SUMMARY_SEARCH_DIALOG("Ledger", "resources/view/sd/ReportWorkerWorkSummarySearchDialog.fxml"),
	//
	RPT_SALES_RETURN_BY_AGENT_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnByAgentSearchDialog.fxml"),
	RPT_SALES_RETURN_BY_CITY_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnByCitySearchDialog.fxml"),
	RPT_SALES_RETURN_BY_CUSTOMER_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnByCustomerSearchDialog.fxml"),
	RPT_SALES_RETURN_BY_DAY_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnByDaySearchDialog.fxml"),
	RPT_SALES_RETURN_BY_MONTH_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnByMonthSearchDialog.fxml"),
	RPT_SALES_RETURN_BY_PROD_CAT_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnByProdCatSearchDialog.fxml"),
	RPT_SALES_RETURN_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnByProdSearchDialog.fxml"),
	RPT_SALES_RETURN_BY_STATE_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnByStateSearchDialog.fxml"),
	RPT_SALES_RETURN_DETAILED_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnDetailedByProdSearchDialog.fxml"),
	RPT_SALES_RETURN_DETAILED_BY_VOUCHER_SEARCH_DIALOG("", "resources/view/sd/RptSalesReturnDetailedByVoucherSearchDialog.fxml"),
	//
	RPT_SALES_BY_AGENT_SEARCH_DIALOG("", "resources/view/sd/RptSalesByAgentSearchDialog.fxml"),
	RPT_SALES_BY_CITY_SEARCH_DIALOG("", "resources/view/sd/RptSalesByCitySearchDialog.fxml"),
	RPT_SALES_BY_CUSTOMER_SEARCH_DIALOG("", "resources/view/sd/RptSalesByCustomerSearchDialog.fxml"),
	RPT_SALES_BY_DAY_SEARCH_DIALOG("", "resources/view/sd/RptSalesByDaySearchDialog.fxml"),
	RPT_SALES_BY_MONTH_SEARCH_DIALOG("", "resources/view/sd/RptSalesByMonthSearchDialog.fxml"),
	RPT_SALES_BY_PROD_CAT_SEARCH_DIALOG("", "resources/view/sd/RptSalesByProdCatSearchDialog.fxml"),
	RPT_SALES_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptSalesByProdSearchDialog.fxml"),
	RPT_SALES_BY_STATE_SEARCH_DIALOG("", "resources/view/sd/RptSalesByStateSearchDialog.fxml"),
	RPT_SALES_DETAILED_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptSalesDetailedByProdSearchDialog.fxml"),
	RPT_SALES_DETAILED_BY_VOUCHER_SEARCH_DIALOG("", "resources/view/sd/RptSalesDetailedByVoucherSearchDialog.fxml"),
	DUE_RCVABLE_BY_SALES_SEARCH_DIALOG("", "resources/view/sd/DueRcvableBySalesSearchDialog.fxml"),
	DUE_RCVABLE_BY_CUSTOMER_SEARCH_DIALOG("", "resources/view/sd/DueRcvableByCustomerSearchDialog.fxml"),
	//
	RPT_SALES_PROFIT_BY_CUSTOMER_SEARCH_DIALOG("", "resources/view/sd/RptSalesProfitByCustomerSearchDialog.fxml"),
	RPT_SALES_PROFIT_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptSalesProfitByProductSearchDialog.fxml"),
	RPT_SALES_PROFIT_BY_SALES_ITEM_SEARCH_DIALOG("", "resources/view/sd/RptSalesProfitBySalesItemSearchDialog.fxml"),
	RPT_SALES_PROFIT_BY_SALES_VOUCHER_SEARCH_DIALOG("", "resources/view/sd/RptSalesProfitBySalesVoucherSearchDialog.fxml"),
	//
	RPT_PURCHASE_RETURN_BY_AGENT_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnByAgentSearchDialog.fxml"),
	RPT_PURCHASE_RETURN_BY_CITY_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnByCitySearchDialog.fxml"),
	RPT_PURCHASE_RETURN_BY_SUPPLIER_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnBySupplierSearchDialog.fxml"),
	RPT_PURCHASE_RETURN_BY_DAY_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnByDaySearchDialog.fxml"),
	RPT_PURCHASE_RETURN_BY_MONTH_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnByMonthSearchDialog.fxml"),
	RPT_PURCHASE_RETURN_BY_PROD_CAT_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnByProdCatSearchDialog.fxml"),
	RPT_PURCHASE_RETURN_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnByProdSearchDialog.fxml"),
	RPT_PURCHASE_RETURN_BY_STATE_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnByStateSearchDialog.fxml"),
	RPT_PURCHASE_RETURN_DETAILED_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnDetailedByProdSearchDialog.fxml"),
	RPT_PURCHASE_RETURN_DETAILED_BY_VOUCHER_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseReturnDetailedByVoucherSearchDialog.fxml"),
	//
	RPT_PURCHASE_BY_AGENT_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseByAgentSearchDialog.fxml"),
	RPT_PURCHASE_BY_CITY_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseByCitySearchDialog.fxml"),
	RPT_PURCHASE_BY_SUPPLIER_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseBySupplierSearchDialog.fxml"),
	RPT_PURCHASE_BY_DAY_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseByDaySearchDialog.fxml"),
	RPT_PURCHASE_BY_MONTH_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseByMonthSearchDialog.fxml"),
	RPT_PURCHASE_BY_PROD_CAT_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseByProdCatSearchDialog.fxml"),
	RPT_PURCHASE_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseByProdSearchDialog.fxml"),
	RPT_PURCHASE_BY_STATE_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseByStateSearchDialog.fxml"),
	RPT_PURCHASE_DETAILED_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseDetailedByProdSearchDialog.fxml"),
	RPT_PURCHASE_DETAILED_BY_VOUCHER_SEARCH_DIALOG("", "resources/view/sd/RptPurchaseDetailedByVoucherSearchDialog.fxml"),
	//
	RPT_ESTIMATE_PENDING_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptEstimatePendingByProdSearchDialog.fxml"),
	RPT_ESTIMATE_PENDING_BY_ACCT_SEARCH_DIALOG("", "resources/view/sd/RptEstimatePendingByAcctSearchDialog.fxml"),
	RPT_ESTIMATE_PENDING_PRODUCT_SEARCH_DIALOG("", "resources/view/sd/RptEstimatePendingProductSearchDialog.fxml"),
	//
	RPT_IO_DET_SEARCH_DIALOG("", "resources/view/sd/RptIoDetSearchDialog.fxml"),
	RPT_IO_SUMM_BY_PROD_CAT_SEARCH_DIALOG("", "resources/view/sd/RptIoSummByProdCatSearchDialog.fxml"),
	RPT_IO_SUMM_BY_PROD_SEARCH_DIALOG("", "resources/view/sd/RptIoSummByProdSearchDialog.fxml"),
	RPT_IO_SUMM_BY_MONTH_SEARCH_DIALOG("", "resources/view/sd/RptIoSummByMonthSearchDialog.fxml"),
	//
	LOGIN("", "resources/view/Login.fxml"),
	MENU_CONFIG("", "resources/view/MenuConfig.fxml"),
	MENU_FLOW_PANE_SV("", "resources/view/MenuFlowPaneSv.fxml"),
	//
	MSG_TEMPLATE_DIALOG("", "resources/view/MsgTemplateDialog.fxml"),
	SALES_MSG_TEMPLATE_DIALOG("", "resources/view/SalesMsgTemplateDialog.fxml"),
	SPLASH_SCREEN("", "resources/view/SplashScreen.fxml"),
	SUPPLIER_PRICE_LIST_SV("", "resources/view/SupplierPriceListSv.fxml"),
	COMPANY_YEAR("Manage Company and Financial Year", "resources/view/ManageCompanyAndYear.fxml"),
	CONTAINER("", "resources/view/Container.fxml"),
	MENU("Menu", "resources/view/Menu.fxml"),
	PRINT_LABEL_DIALOG("Menu", "resources/view/PrintLabelDialog.fxml"),
	PRODUCT_STATEMENT_OPEN_TYPE_DIALOG("", "resources/view/ProductStatementOpenTypeDialog.fxml"),
	PUSA_AMT_AFTER_ITEM_DISC("Menu", "resources/view/PusaAmtAfterItemDisc.fxml"),
	PUSA_AMT_TAXABLE("Menu", "resources/view/PusaAmtTaxable.fxml"),
	PUSA_ITEM("", "resources/view/PusaItem.fxml"),
	PUSA_ITEM_FORM("", "resources/view/PusaItemForm.fxml"),
	PUSA_OTH_CH_NON_TAXABLE("Menu", "resources/view/PusaOthChNonTaxable.fxml"),
	PUSA_OTH_CH_NON_TAXABLE_ROW("Menu", "resources/view/PusaOthChNonTaxableRow.fxml"),
	PUSA_OTH_CH_ON_ITEM("Menu", "resources/view/PusaOthChOnItem.fxml"),
	PUSA_OTH_CH_ON_ITEM_ROW("Menu", "resources/view/PusaOthChOnItemRow.fxml"),
	PUSA_OTH_CH_ON_ITEM_SYSTEM("Menu", "resources/view/PusaOthChOnItemSystem.fxml"),
	PUSA_OTH_CH_ON_ITEM_SYSTEM_ROW("Menu", "resources/view/PusaOthChOnItemSystemRow.fxml"),
	PUSA_OTH_CH_TAXABLE("Menu", "resources/view/PusaOthChTaxable.fxml"),
	PUSA_OTH_CH_TAXABLE_ROW("Menu", "resources/view/PusaOthChTaxableRow.fxml"),
	PUSA_TAX("", "resources/view/PusaTax.fxml"),
	PUSA_TOTAL("", "resources/view/PusaTotal.fxml"),
	//
	PUSA_AMT_AFTER_ITEM_DISC2("Menu", "resources/view/PusaAmtAfterItemDisc2.fxml"),
	PUSA_AMT_TAXABLE2("Menu", "resources/view/PusaAmtTaxable2.fxml"),
	PUSA_ITEM2("", "resources/view/PusaItem2.fxml"),
	PUSA_ITEM_FORM2("", "resources/view/PusaItemForm2.fxml"),
	PUSA_OTH_CH_NON_TAXABLE2("Menu", "resources/view/PusaOthChNonTaxable2.fxml"),
	PUSA_OTH_CH_NON_TAXABLE_ROW2("Menu", "resources/view/PusaOthChNonTaxableRow2.fxml"),
	PUSA_OTH_CH_ON_ITEM2("", "resources/view/PusaOthChOnItem2.fxml"),
	PUSA_OTH_CH_ON_ITEM_ROW2("", "resources/view/PusaOthChOnItemRow2.fxml"),
	PUSA_OTH_CH_ON_ITEM_SYSTEM2("", "resources/view/PusaOthChOnItemSystem2.fxml"),
	PUSA_OTH_CH_ON_ITEM_SYSTEM_ROW2("", "resources/view/PusaOthChOnItemSystemRow2.fxml"),
	PUSA_OTH_CH_TAXABLE2("", "resources/view/PusaOthChTaxable2.fxml"),
	PUSA_OTH_CH_TAXABLE_ROW2("", "resources/view/PusaOthChTaxableRow2.fxml"),
	PUSA_TAX2("", "resources/view/PusaTax2.fxml"),
	PUSA_TOTAL2("", "resources/view/PusaTotal2.fxml"),
	//
	SALES_PRINT_TYPE_DIALOG("", "resources/view/SalesPrintTypeDialog.fxml"),
	SAVE_BUTTON_BAR("", "resources/view/SaveButtonBar.fxml"),
	SELECT_COMPANY_MSG("", "resources/view/SelectCompanyMsg.fxml"),
	TOP_BAR("", "resources/view/TopBar.fxml"),
	SINGLE_GENERAL_MENU("", "resources/view/SingleGeneralMenu.fxml"),
	SUPPLIER_SELECTION_SV("", "resources/view/SupplierSelectionSv.fxml"),
	SYSTEM_MENU("System Menu", "resources/view/SystemMenu.fxml"),
	BROWSER("Browser", "resources/view/Browser.fxml");

	private final String title;
	private final String path;

	private FXMLLayouts(String title, String path)
	{
		this.title = title;
		this.path = path;
	}

	public String getTitle()
	{
		return title;
	}

	public String getPath()
	{
		return path;
	}
}
