package com.hemsw.asasaapi.veenal.enums;

public enum KbShortcutEnum
{
	ADD(1, "add"),
	EDIT(2, "edit"),
	DELETE(3, "delete"),
	OPEN(4, "open"),
	VIEW(5, "view"),
	PRINT(6, "print"),
	EXPORT(7, "export"),
	FIND(8, "find"),
	CLEAR_FILTER(9, "clear_filter"),
	OPEN_COL_SETTING(10, "open_col_setting"),
	HIDE_ROW(11, "hide_row"),
	UNHIDE_ROW(12, "unhide_row"),
	FOCUS_SEARCH(13, "focus_search"),
	FOCUS_TABLE(14, "focus_table"),
	GO_TO_DATE(15, "go_to_date"),
	SEARCH(16, "search"),
	CLEAR_SEARCH(17, "clear_search"),
	BACK(18, "back"),
	COMPANY_YEAR(19, "company_year"),
	SYSTEM_SETTINGS(20, "system_settings"),
	NEXT_ENTRY(21, "next_entry"),
	PREVIOUS_ENTRY(22, "previous_entry"),
	SAVE(23, "save"),
	CANCEL(24, "cancel"),
	ADD_DROPDOWN_ITEM(25, "add_dropdown_item"),
	EDIT_DROPDOWN_ITEM(26, "edit_dropdown_item"),
	ADD_EDIT_DROPDOWN_ITEM(27, "add_edit_dropdown_item"),
	JUMP_TO_NEXT_SECTION(28, "jump_to_next_section"),
	EDIT_ITEM(29, "edit_item"),
	DELETE_ITEM(30, "delete_item"),
	MOVE_ITEM_UP(31, "move_item_up"),
	MOVE_ITEM_DOWN(32, "move_item_down"),
	SAVE_ITEM(33, "save_item"),
	SEND_MSG_WA(34, "send_msg_wa"),
	OPEN_RELATED_REPORTS(35, "open_related_reports"),
	USER(36, "user"),
	USER_ADD(37, "user_add"),
	ACCESS_ROLE(38, "access_role"),
	ACCESS_ROLE_ADD(39, "access_role_add"),
	TASK(40, "task"),
	TASK_ADD(41, "task_add"),
	COMMNC_BOOK(42, "commnc_book"),
	OPEN_COMMNC_BOOK_OPT(43, "open_commnc_book_opt"),
	REMINDER(44, "reminder"),
	REMINDER_ADD(45, "reminder_add"),
	REMINDER_SNOOZE(46, "reminder_snooze"),
	REMINDER_TURN_OFF(47, "reminder_turn_off"),
	REMINDER_RESCHED(48, "reminder_resched"),
	COMMNC(49, "commnc"),
	COMMNC_ADD(50, "commnc_add"),
	COMMNC_ASSIGN_TO(51, "commnc_assign_to"),
	LEAD(52, "lead"),
	LEAD_ADD(53, "lead_add"),
	ADD_REMARK_OPT(54, "add_remark_opt"),
	ADD_REMINDER_OPT(55, "add_reminder_opt"),
	ACCT_BOOK(56, "acct_book"),
	DAY_BOOK(57, "day_book"),
	CDP(58, "cdp"),
	CDP_ADD(59, "cdp_add"),
	JOURNAL(60, "journal"),
	JOURNAL_ADD(61, "journal_add"),
	CONTRA(62, "contra"),
	CONTRA_ADD(63, "contra_add"),
	RECEIPT(64, "receipt"),
	RECEIPT_ADD(65, "receipt_add"),
	PAYMENT(66, "payment"),
	PAYMENT_ADD(67, "payment_add"),
	SALES(68, "sales"),
	SALES_ADD(69, "sales_add"),
	SALES_RETURN(70, "sales_return"),
	SALES_RETURN_ADD(71, "sales_return_add"),
	PI(72, "pi"),
	PI_ADD(73, "pi_add"),
	PI_TO_SO(74, "pi_to_so"),
	PI_TO_ESTIMATE(75, "pi_to_estimate"),
	PI_TO_SALES(76, "pi_to_sales"),
	SALES_ORDER(77, "sales_order"),
	SALES_ORDER_ADD(78, "sales_order_add"),
	SO_TO_ESTIMATE(79, "so_to_estimate"),
	SO_TO_PI(80, "so_to_pi"),
	SALES_ORDER_TO_SALES(81, "sales_order_to_sales"),
	ESTIMATE(82, "estimate"),
	ESTIMATE_ADD(83, "estimate_add"),
	ESTIMATE_TO_SO(84, "estimate_to_so"),
	ESITMATE_TO_PI(85, "esitmate_to_pi"),
	ESTIMATE_TO_SALES(86, "estimate_to_sales"),
	PURCHASE(87, "purchase"),
	PURCHASE_ADD(88, "purchase_add"),
	PURCHASE_RETURN(89, "purchase_return"),
	PURCHASE_RETURN_ADD(90, "purchase_return_add"),
	PURCHASE_ORDER(91, "purchase_order"),
	PURCHASE_ORDER_ADD(92, "purchase_order_add"),
	COMM_VOU(93, "comm_vou"),
	COMM_VOU_ADD(94, "comm_vou_add"),
	CASH_DISC_VOU(95, "cash_disc_vou"),
	CASH_DISC_VOU_ADD(96, "cash_disc_vou_add"),
	BANK(97, "bank"),
	BANK_ADD(98, "bank_add"),
	CUSTOMER(99, "customer"),
	CUSTOMER_ADD(100, "customer_add"),
	SUPPLIER(101, "supplier"),
	SUPPLIER_ADD(102, "supplier_add"),
	AGENT(103, "agent"),
	AGENT_ADD(104, "agent_add"),
	ACCT(105, "acct"),
	ACCT_ADD(106, "acct_add"),
	PRINT_ENVELOPE(107, "print_envelope"),
	ACCT_TYPE(108, "acct_type"),
	ACCT_TYPE_ADD(109, "acct_type_add"),
	INV_ADJUST(110, "inv_adjust"),
	INV_ADJUST_ADD(111, "inv_adjust_add"),
	COMM_LIST(112, "comm_list"),
	COMM_LIST_ADD(113, "comm_list_add"),
	SALES_PRICE_LIST(114, "price_list"),
	SALES_PRICE_LIST_ADD(115, "price_list_add"),
	SERVICE(116, "service"),
	SERVICE_ADD(117, "service_add"),
	PRODUCT(118, "product"),
	PRODUCT_ADD(119, "product_add"),
	PROD_OTH_CHARGE(120, "prod_oth_charge"),
	PROD_OTH_CHARGE_ADD(121, "prod_oth_charge_add"),
	TAX_CAT(122, "tax_cat"),
	TAX_CAT_ADD(123, "tax_cat_add"),
	PROD_CAT(124, "prod_cat"),
	PROD_CAT_ADD(125, "prod_cat_add"),
	UNIT(126, "unit"),
	UNIT_ADD(127, "unit_add"),
	RPT_SALES_RETURN_BY_MONTH(128, "rpt_sales_return_by_month"),
	RPT_SALES_RETURN_BY_DAY(129, "rpt_sales_return_by_day"),
	RPT_SALES_RETURN_BY_CUSTOMER(130, "rpt_sales_return_by_customer"),
	RPT_SALES_RETURN_BY_CATEGORY(131, "rpt_sales_return_by_category"),
	RPT_SALES_RETURN_BY_PRODUCT(132, "rpt_sales_return_by_product"),
	RPT_SALES_RETURN_BY_CITY(133, "rpt_sales_return_by_city"),
	RPT_SALES_RETURN_BY_STATE(134, "rpt_sales_return_by_state"),
	RPT_SALES_RETURN_BY_AGENT(135, "rpt_sales_return_by_agent"),
	RPT_SALES_BY_MONTH(136, "rpt_sales_by_month"),
	RPT_SALES_BY_DAY(137, "rpt_sales_by_day"),
	RPT_SALES_BY_CUSTOMER(138, "rpt_sales_by_customer"),
	RPT_SALES_BY_CATEGORY(139, "rpt_sales_by_category"),
	RPT_SALES_BY_PRODUCT(140, "rpt_sales_by_product"),
	RPT_SALES_BY_CITY(141, "rpt_sales_by_city"),
	RPT_SALES_BY_STATE(142, "rpt_sales_by_state"),
	RPT_SALES_BY_AGENT(143, "rpt_sales_by_agent"),
	RPT_PURCHASE_RETURN_BY_MONTH(144, "rpt_purchase_return_by_month"),
	RPT_PURCHASE_RETURN_BY_DAY(145, "rpt_purchase_return_by_day"),
	RPT_PURCHASE_RETURN_BY_SUPPLIER(146, "rpt_purchase_return_by_supplier"),
	RPT_PURCHASE_RETURN_BY_CATEGORY(147, "rpt_purchase_return_by_category"),
	RPT_PURCHASE_RETURN_BY_PRODUCT(148, "rpt_purchase_return_by_product"),
	RPT_PURCHASE_RETURN_BY_CITY(149, "rpt_purchase_return_by_city"),
	RPT_PURCHASE_RETURN_BY_STATE(150, "rpt_purchase_return_by_state"),
	RPT_PURCHASE_BY_MONTH(151, "rpt_purchase_by_month"),
	RPT_PURCHASE_BY_DAY(152, "rpt_purchase_by_day"),
	RPT_PURCHASE_BY_SUPPLIER(153, "rpt_purchase_by_supplier"),
	RPT_PURCHASE_BY_CATEGORY(154, "rpt_purchase_by_category"),
	RPT_PURCHASE_BY_PRODUCT(155, "rpt_purchase_by_product"),
	RPT_PURCHASE_BY_CITY(156, "rpt_purchase_by_city"),
	RPT_PURCHASE_BY_STATE(157, "rpt_purchase_by_state"),
	RPT_ESTIMATE_PENDING_PRODUCTS(158, "rpt_estimate_pending_products"),
	DUE_RCVABLE_BY_CUSTOMER(159, "due_rcvable_by_customer"),
	DUE_RCVABLE_BY_SALES(160, "due_rcvable_by_sales"),
	RPT_IO_SUMM_BY_PROD_CAT(161, "rpt_io_summ_by_prod_cat"),
	RPT_IO_SUMM_BY_MONTH(162, "rpt_io_summ_by_month"),
	RPT_IO_SUMM_BY_PROD(163, "rpt_io_summ_by_prod"),
	RPT_IO_DET(164, "rpt_io_det"),
	LEDGER(165, "ledger"),
	TRIAL_BALANCE(166, "trial_balance"),
	TRADING_ACCT(167, "trading_acct"),
	PL_ACCT(168, "pl_acct"),
	BALANCE_SHEET(169, "balance_sheet"),
	GST_LEDGER(170, "gst_ledger"),
	INVENTORY_LEDGER(171, "inventory_ledger"),
	CURRENT_STOCK(172, "current_stock"),
	CURRENT_STOCK_VAL(173, "current_stock_val"),
	LOW_STOCK(174, "low_stock"),
	SALES_ANALYSIS(175, "sales_analysis"),
	CASH_DISC_VOU_LEDGER(176, "cash_disc_vou_ledger"),
	CASH_DISC_VOU_LEDGER_2(177, "cash_disc_vou_ledger_2"),
	COMM_VOU_LEDGER(178, "comm_vou_ledger"),
	SALES_ORDER_PENDING(179, "sales_order_pending"),
	PURCHASE_ORDER_PENDING(180, "purchase_order_pending"),
	SCHEME(181, "scheme"),
	SCHEME_ADD(182, "scheme_add"),
	TRANSPORTER(183, "transporter"),
	TRANSPORTER_ADD(184, "transporter_add"),
	TAX_CAL_RATE(185, "tax_cal_rate"),
	TAX_CAL_RATE_ADD(186, "tax_cal_rate_add"),
	TAX(187, "tax"),
	TAX_ADD(188, "tax_add"),
	MSG_TEMPLATE(189, "msg_template"),
	MSG_TEMPLATE_ADD(190, "msg_template_add"),
	COMPANY_INFO(191, "company_info"),
	COMPANY_PROFILE(192, "company_profile"),
	COMPANY_PROFILE_ADD(193, "company_profile_add"),
	VOU_OTH_CH(194, "vou_oth_ch"),
	VOU_OTH_CH_ADD(195, "vou_oth_ch_add"),
	IMPORT_DATA(196, "import_data"),
	MENU_CONFIG(197, "menu_config"),;

	private final int id;
	private final String key;

	private KbShortcutEnum(int id, String key)
	{
		this.id = id;
		this.key = key;
	}

	public int getId()
	{
		return id;
	}

	public String getKey()
	{
		return key;
	}

}
