package com.hemsw.asasaapi.veenal.enums;

public enum ListMenu
{
	DAY_BOOK(1),
	VOU_OTH_CHARGE(2),
	PROD(3),
	INV_ADJUST(4),
	ACCT_TYPE(5),
	ACCT(6),
	AGENT(7),
	SUPPLIER(8),
	CUSTOMER(9),
	BANK(10),
	PURCHASE_ORDER(11),
	PURCHASE(12),
	PURCHASE_RETURN(13),
	SALES_ORDER(14),
	PI(15),
	SALES(16),
	SALES_RETURN(17),
	PAYMENT(18),
	RECEIPT(19),
	CONTRA(20),
	CASH_DISC_VOU(21),
	COMM_VOU(22),
	CURRENT_STOCK_BY_CAT(23),
	CURRENT_STOCK_VAL(24),
	LOW_STOCK(25),
	JOURNAL(26),
	CDP_JOURNAL_VOU(27),
	SALES_ORDER_PENDING_DET(28),
	SALES_ORDER_PENDING_BY_CUST(29),
	SALES_ORDER_PENDING_BY_PROD(30),
	PURCHASE_ORDER_PENDING_DET(31),
	PURCHASE_ORDER_PENDING_BY_SUPPLIER(32),
	PURCHASE_ORDER_PENDING_BY_PROD(33),
	ORDER_ADJUST(34),
	ESTIMATE(35),
	LEAD(36),
	COMMNC(37),
	REMINDER(38),
	DUE_RCVABLE_BY_SALES(39),
	DUE_RCVABLE_BY_CUSTOMER(40),
	RPT_ESTIMATE_PENDING_PRODUCT(41),;

	private final int id;

	ListMenu(final int id)
	{
		this.id = id;
	}

	public int getId()
	{
		return id;
	}

}
